name: torch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - accelerate=1.10.1=pyhcf101f3_0
  - albucore=0.0.24=pyhd8ed1ab_0
  - albumentations=2.0.8=pyhd8ed1ab_0
  - annotated-types=0.6.0=py310h06a4308_0
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=py310h06a4308_0
  - cffi=2.0.0=py310h4eded50_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.9=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - eigen=3.4.0=hdb19cb5_0
  - et_xmlfile=2.0.0=py310h06a4308_0
  - eval-type-backport=0.2.2=py310h06a4308_1
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=hc01ab50_4
  - filelock=3.17.0=py310h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py310hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fsspec=2025.7.0=py310he3bba80_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.24.12=hc146dc4_1
  - gstreamer=1.24.12=hb6d4d65_1
  - gstreamer-orc=0.4.41=h5eee18b_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - hf-xet=1.1.8=py310h84c0859_0
  - huggingface_hub=0.34.4=py310h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jinja2=3.1.6=py310h06a4308_0
  - joblib=1.5.2=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - kiwisolver=1.4.8=py310h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.8.1=h13d4d48_0
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.14.1.1=4
  - libcups=2.4.2=h252cb56_2
  - libcurand=10.3.10.19=0
  - libcurl=8.15.0=hc1efc7f_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.16=h5eee18b_3
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=0
  - libnvfatbin=12.9.82=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=h02b6914_2
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib=3.10.6=py310h06a4308_1
  - matplotlib-base=3.10.6=py310h71dd3da_1
  - mesalib=25.1.5=h31e3550_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.5=h7934f7d_0
  - networkx=3.4.2=py310h06a4308_0
  - numexpr=2.11.0=py310hf4471f9_0
  - numpy=2.0.1=py310h5f9d8c6_1
  - numpy-base=2.0.1=py310hb5e798b_1
  - ocl-icd=2.3.2=h5eee18b_1
  - opencv=4.10.0=py310h6030d24_7
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.10=he9288cc_1
  - openpyxl=3.1.5=py310h5eee18b_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py310h06a4308_0
  - pandas=2.3.3=py310h505adc9_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py310hac6e08b_1
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - psutil=7.0.0=py310hee96239_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.23=py310h06a4308_0
  - pydantic=2.11.9=py310h06a4308_0
  - pydantic-core=2.33.2=py310hc6f7160_0
  - pyparsing=3.2.0=py310h06a4308_0
  - pyqt=6.7.1=py310h8dad735_2
  - pyqt6-sip=13.9.1=py310h6ce4db3_2
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.4.0=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py310h06a4308_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - qtbase=6.7.3=h10a5587_4
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h5a8de97_1
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebsockets=6.7.3=h7934f7d_1
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py310h06a4308_0
  - safetensors=0.5.3=py310h922eef2_0
  - scikit-learn=1.7.2=py310h505adc9_0
  - scipy=1.15.3=py310h525edd1_0
  - seaborn=0.13.2=py310h06a4308_3
  - setuptools=80.9.0=py310h06a4308_0
  - simsimd=6.5.0=py310ha75aee5_0
  - sip=6.10.0=py310h6a678d5_0
  - six=1.17.0=py310h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - stringzilla=3.12.6=py310h7c4b9e2_1
  - sympy=1.14.0=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=hb0d2e87_3
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - timm=1.0.22=pyhcf101f3_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py310h06a4308_0
  - torchaudio=2.4.0=py310_cu124
  - torchtriton=3.0.0=py310
  - torchvision=0.19.0=py310_cu124
  - tornado=6.5.1=py310h5eee18b_0
  - tqdm=4.67.1=py310h2f386ee_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing-inspection=0.4.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - coloredlogs==15.0.1
      - coral-pytorch==1.4.0
      - flatbuffers==25.9.23
      - humanfriendly==10.0
      - ml-dtypes==0.5.4
      - onnx==1.20.0
      - onnxruntime==1.23.2
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - protobuf==6.33.2
      - pycocotools==2.0.11
      - pytorch-model-summary==0.1.2
      - segment-anything==1.0
      - thop==0.1.1-2209072238
      - ultralytics==8.3.240
      - ultralytics-thop==2.0.18
prefix: /home/mit/anaconda3/envs/torch
